---
apiVersion: v1
kind: Pod
metadata:
  name: web-app
  labels:
    app: svs-web-httpd
spec:
  containers:
  - name: web-server
    image: ghostsvsghost/web_httpd:latest
    ports:
      - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: web-app-svc
spec:
  selector:
    app: svs-web-httpd
  type: NodePort
  ports:
    - targetPort: 80
      port: 8080
      nodePort: 30002