---
# tasks file for mysql-install
- name: Install mysql Packages
  apt: name={{ item }} update_cache=yes state=latest
  loop: [ 'mysql-server' ]
  tags:
  - mysql-setup

- name: Sets the root password
  mysql_user:
    login_user: "{{ mysql_root_name }}"
    login_password: "{{ mysql_root_password }}"
    name: "{{ mysql_root_name }}"
    password: "{{ mysql_root_password }}"
    host_all: yes
    login_unix_socket: /var/run/mysqld/mysqld.sock
    state: present
  tags:
  - mysql-setup

- name: Removes the MySQL test database
  mysql_db:
    name: test
    state: absent
    login_user: "{{ mysql_root_name }}"
    login_password: "{{ mysql_root_password }}"
    login_unix_socket: /var/run/mysqld/mysqld.sock
  tags:
  - mysql-setup

- name: Create the MySQL wordpress database
  mysql_db:
    name: wordpress
    state: present
    login_user: "{{ mysql_root_name }}"
    login_password: "{{ mysql_root_password }}"
    login_unix_socket: /var/run/mysqld/mysqld.sock
  tags:
  - mysql-setup

- name: Create wordpress user
  mysql_user:
    login_user: "{{ mysql_root_name }}"
    login_password: "{{ mysql_root_password }}"
    login_unix_socket: /var/run/mysqld/mysqld.sock
    name: "{{ wordpress_user_name }}"
    password: "{{ wordpress_user_password }}"
    state: present
    priv: "wordpress.*: ALL,GRANT"
  tags:
  - mysql-setup

- name: Removes all anonymous user accounts
  mysql_user:
    name: ''
    host_all: yes
    state: absent
    login_user: "{{ mysql_root_name }}"
    login_password: "{{ mysql_root_password }}"
    login_unix_socket: /var/run/mysqld/mysqld.sock
  tags:
  - mysql-setup








