name: Docker Image CI

on:
  push:
    branches: [ master ]
    paths:
    - 'Lesson3-hw/Dockerfile'
    - 'Lesson3-hw/index.html'
    - 'Lesson7-hw/tg-bot/my-bot/Dockerfile'
  pull_request:
    branches: [ master ]
    paths:
    - 'Lesson3-hw/Dockerfile'
    - 'Lesson3-hw/index.html'
    - 'Lesson7-hw/tg-bot/my-bot/Dockerfile'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASS }}

    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: cd Lesson3-hw && docker build . -f Dockerfile -t ${{ secrets.DOCKERHUB_USERNAME }}/web_httpd:latest

    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: cd Lesson7-hw/tg-bot/my-bot/ && docker build . -f Dockerfile -t ${{ secrets.DOCKERHUB_USERNAME }}/pytgweatherbot:latest

    - name: Push docker image to Docker Hub
      run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/web_httpd:latest